language: java
services:
  - docker
addons:
  ssh_known_hosts: start.vertx.io
branches:
  only:
    - master
    - prod
jdk: openjdk11
jobs:
  include:
    - stage: deploy
      if: type = push AND branch = prod
      before_install:
        - openssl aes-256-cbc -K $encrypted_08b377984515_key -iv $encrypted_08b377984515_iv -in deploy_rsa.enc -out deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 deploy_rsa
        - ssh-add deploy_rsa
      install:
        - ./gradlew assemble
      script:
        - bash .travis.deploy.bash
notifications:
  email:
    recipients:
      - secure: cElG46XlYoviM6K/OsEjTkCwUxa1Fj5lhCuGUaIro2VqMNued/vJkAvFZTGnDjuhZXb7q6AfutHX6/f/goEFH5kAeolYpKl+ose/bBaIQv8afiBhcSsj4d87CYnnIoSHAx47O0ryJlEVoftgcUsGYp994HSwDbEF2WOaYEjVXh93Or561rI9U7e1pLv5qP+Im0cb+/oHRE25W7D/P+Wp8rYeSFvYMBIu85BXyxdjyupVzOF9lfTVFg4e/cq0iasZyV4VM6YYhOvb3mA9zphumCMGa/tNgAkoNRxP9nQgwES7mRFxMttxFxowCCx+8aIAlnQHc76pnipP57LsV8eTf0XRPmDQ24jDdf96i7oDkKWyS4cA/IheQymCdlBQB7wsymuo7K9CJEEcXz57XRz20z3JFBIOAkAO+PdFec9LNDTQTQBk9xDbu+fQg3wG6Nv+yhH8pZDDuoxFSZrvi17oaAh4XfCAwJiIvLICuDeBZ6yWO+Ey29aE+7wbNDDQDMhEGTq5ws0uhrPxS19JzikHGWjB21aqpBMq+B9eV6xgV4SJg9uasgkPG/HGd9YSLVB7o8iSzjVwKp5sdbw14wzgdnEY7pX6yAX3gQ/11XP+7YuNaVdQgbhqiOBSRiXnSBKvJK3+YsRrDYRu0usGZzexLwapiVNnSapHfURtZOKtpJA=
    on_success: always
    on_failure: always
